name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t nibhav/pet_store_app_01:latest .
    - name: Push to Dockerhub
      run: docker push nibhav/pet_store_app_01:latest
    
    - name: Cleanup old deploy.sh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: rm -rf /home/ubuntu/deploy.sh

    - name: Copy deploy script to EC2
      uses: appleboy/scp-action@v0.1.7   #action from market created by author appleboy to copy script to ec2
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_SSH_KEY}}
        target: /home/ubuntu/
        strip_components: 1

    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@v1.0.3   #action from market created by author appleboy to deploy script to ec2
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_SSH_KEY}}
        script: |
          chmod +x ~/deploy.sh
          sudo ~/deploy.sh

